import type { Metadata } from "next";
import { Irish_Grover, Montserrat } from "next/font/google";
import "./globals.css";

const irish = Irish_Grover({
  subsets: ["latin"],
  variable: "--font-irish",
  weight: "400",
});
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-mont",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${irish.variable} ${montserrat.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
